# ReadTheDocs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Python environment
python:
  install:
    - method: pip
      path: .
      extra: dev

# Documentation build
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

# Enable PDF and EPUB builds
formats:
  - pdf
  - epub

# Search configuration (ignore build directories)
search:
  ignore:
    - /docs/_build/
    - /docs/.doctrees/
